[package]
name = "hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
axum = "0.8.8"
dotenvy = "0.15.7"
serde = "1.0.228"
sqlx = "0.8.6"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tower = "0.5.3"
uuid = "1.19.0"
